title = "Joao Macedo WebAssembly Blog"
# logo = "URL to logo"
base_url = "https://spin-deploy.joao-website.hippo.joaodemacedo.com"
about = "My name is João De Macedo, and this is my WebAssembly Blog."

[extra]
copyright = "2022 João De Macedo"
github = "https://github.com/joaogdemacedo"
twitter = "https://twitter.com/joaodemacedo134"

date_style = "%B %e, %Y"
